# Generated by Django 3.2.8 on 2021-10-24 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_auto_20211023_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='user',
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood_self_grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
