# Generated by Django 3.2.8 on 2021-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_auto_20211023_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
